In [1]:
import torch


import reBert.layers

In [2]:
config = {
    'max_len': 10,
    'd_model': 10,
    'device': 'cpu',
}

embL = reBert.layers.EmbeddingLayer(config)

In [3]:
embL._to_position_mask()

AttributeError: 'EmbeddingLayer' object has no attribute '_to_position_mask'

In [3]:
input_ids = torch.randn(1, 2, 10)
seg = torch.randint(0, 2, (1, 2))

print(input_ids)
print(seg)

emb = embL(input_ids, seg)

print(emb)

tensor([[[-2.5104e-01, -7.1988e-01,  1.6825e+00, -5.2888e-02,  1.0978e+00,
           1.6272e-02,  5.1896e-01, -1.1197e+00, -4.6223e-01,  1.7740e+00],
         [-5.3755e-01, -1.4982e-01,  3.8052e-01,  4.6862e-01,  7.4065e-01,
          -3.4490e-01, -2.2973e-01, -5.5952e-01,  1.3529e+00,  5.6981e-04]]])
tensor([[0, 0]])
tensor([[0, 1]])


RuntimeError: No active exception to reraise