In [1]:
import torch


import reBert.layers
import reBert.layerUtil

In [2]:
config = {
    'max_len': 10,
    'd_model': 10,
    'n_heads': 10,
    'device': 'cpu',
}

embL = reBert.layers.EmbeddingLayer(config)

multiHeadAtt = reBert.layers.MultiHeadAttention(config)

In [3]:
input_ids = torch.randn(2, 2, 10)
input_ids = torch.cat([input_ids, torch.zeros(2, 1, 10)], dim=1)
seg = torch.randint(0, 2, (2, 3))

print(input_ids)
print(seg)

emb = embL(input_ids, seg)
atten_pad_mask = reBert.layerUtil.get_attention_pad_mask(input_ids)

print(emb)
print(atten_pad_mask)


query_att = multiHeadAtt(emb, emb, emb, atten_pad_mask)
print(query_att)

tensor([[[-0.6532, -2.4351,  0.1867,  0.2643,  1.0322, -0.0057, -0.6713,
           0.3436, -0.3654, -1.0840],
         [ 0.6542, -0.3158,  0.2519,  0.4760, -0.6915, -0.7987, -2.3046,
          -1.0690, -0.2602,  0.0329],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000]],

        [[ 2.0443,  1.1085, -1.2256,  0.4137, -0.2924,  0.5072,  0.3789,
           1.4590,  1.3254,  0.1112],
         [-0.3366,  0.8236,  0.3653,  0.8393, -1.7538, -0.7458,  0.3562,
           0.6700,  0.0143,  0.3703],
         [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
           0.0000,  0.0000,  0.0000]]])
tensor([[0, 0, 0],
        [0, 0, 1]])
tensor([[[-1.6492, -1.0385,  1.5374,  0.5543,  1.3015,  0.3170, -1.1002,
           0.2909, -0.5642,  0.3508],
         [-0.0854,  0.6812,  0.7113,  0.9168, -0.0626, -0.3767, -2.3023,
          -0.7876, -0.1423,  1.4475],
         [-0.5434,  1.1567,  2.1503, -0.6077,  0.2132, -0.0357, -1.00